image: java:8-jdk
stages:
    - build
    - test
    - deploy
    
before_script:
  - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
cache:
    paths:
    - ".gradle/wrapper"
    - ".gradle/caches"
    
build:
    stage: build
    script: 
    #- mvn clean package -Drevision=$CI_COMMIT_REF_NAME-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA
    - ./gradle assemble
    - mkdir plugins
    - cd plugins
    - mkdir update
    - cd ..
    - cp target/*.jar plugins/update/Languagy.jar
    artifacts:
        name: "Languagy"
        paths:
        - "target/"
        - "plugins/update/*.jar"
        expire_in: 1 week
    allow_failure: false
    
test:
    stage: test
    script: 
    - ./gradlew check
    allow_failure: true
    
deploy:
    stage: deploy
    only:
        refs: 
            - master
    script: 
        #- apt-get --quiet update 
        #- apt-get --quiet install ftp
        - apt-get update -qy
        - apt-get install -y lftp
        - cd plugins
        - cd update
        - ls
        - cd ..
        - cd ..
        - lftp -e "set ssl:verify-certificate no; open 158.69.5.237; user $MC_USERNAME_MAIN $MC_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete plugins/update/ plugins/update/; bye"
deploy_test:
    stage: deploy
    only:
        - branches
    except:
        - master
    script: 
        - apt-get --quiet update 
        - apt-get --quiet install ftp
        - sh transfer.sh $MC_USERNAME_MAIN $MC_PASSWORD