image: gradle:latest
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - gradle wrapper --gradle-version 5.6.2
stages:
    - build
    - test
build:
    stage: build
    tags:
    - gradle
    script:
    - ./gradlew shadowJar
    artifacts:
        paths:
        - build/libs/*.jar
        expire_in: 1 week
    only:
    - master
test:
    stage: test
    tags:
    - gradle
    script: gradle check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
        - build
        - .gradle