image: java:8-jdk
stages:
    - build
    - test
    - deploy
    
before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
cache:
paths:
    - .gradle/wrapper
    - .gradle/caches
    
build:
    stage: build
    script: 
    #- mvn clean package -Drevision=$CI_COMMIT_REF_NAME-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA
    - ./gradlew assemble
    - mkdir generated_jar
    - cp target/*.jar generated_jar/Languagy.jar
    artifacts:
        name: "Languagy"
        paths:
        - "target/"
        - "generated_jar/*.jar"
        expire_in: 1 week
    allow_failure: false
    
test:
    stage: test
    script: 
    - ./gradlew check
    allow_failure: true
    
deploy:
    stage: deploy
    only:
        refs: 
            - master
    script: 
        - apt-get --quiet update 
        - apt-get --quiet install ftp
        - sh transfer.sh $MC_USERNAME_MAIN $MC_PASSWORD
deploy_test:
    stage: deploy
    only:
        - branches
    except:
        - master
    script: 
        - apt-get --quiet update 
        - apt-get --quiet install ftp
        - sh transfer.sh $MC_USERNAME_MAIN $MC_PASSWORD